/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;
import java.awt.*;
import javax.swing.border.LineBorder;
/**
 *
 * @author therax
 */
public class CalculatorDragDrop extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorDragDrop
     */
    double Number1;
    double Number2;
    double Result;
    String Op;
    public CalculatorDragDrop() {
        initComponents();
    }
    LineBorder border1 = new LineBorder(Color.RED, 1);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Screen = new javax.swing.JTextField();
        backspace = new javax.swing.JButton();
        Cbtn = new javax.swing.JButton();
        CEbtn = new javax.swing.JButton();
        PlusBtn = new javax.swing.JButton();
        Sevenbtn = new javax.swing.JButton();
        Eightbtn = new javax.swing.JButton();
        Ninebtn = new javax.swing.JButton();
        LessBtn = new javax.swing.JButton();
        FourBtn = new javax.swing.JButton();
        FiveBtn = new javax.swing.JButton();
        SixBtn = new javax.swing.JButton();
        Timebtn = new javax.swing.JButton();
        OneBtn = new javax.swing.JButton();
        TwoBtn = new javax.swing.JButton();
        ThreeBtn = new javax.swing.JButton();
        DivideBtn = new javax.swing.JButton();
        ZeroBtn = new javax.swing.JButton();
        DotBtn = new javax.swing.JButton();
        EqualBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Screen.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Screen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Screen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Screen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScreenMouseClicked(evt);
            }
        });

        backspace.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        backspace.setText("◀");
        backspace.setMaximumSize(new java.awt.Dimension(33, 33));
        backspace.setMinimumSize(new java.awt.Dimension(33, 33));
        backspace.setPreferredSize(new java.awt.Dimension(24, 24));
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        Cbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Cbtn.setText("c");
        Cbtn.setMaximumSize(new java.awt.Dimension(33, 33));
        Cbtn.setMinimumSize(new java.awt.Dimension(33, 33));
        Cbtn.setPreferredSize(new java.awt.Dimension(24, 24));
        Cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbtnActionPerformed(evt);
            }
        });

        CEbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        CEbtn.setText("CE");
        CEbtn.setMaximumSize(new java.awt.Dimension(33, 33));
        CEbtn.setMinimumSize(new java.awt.Dimension(33, 33));
        CEbtn.setPreferredSize(new java.awt.Dimension(24, 24));
        CEbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEbtnActionPerformed(evt);
            }
        });

        PlusBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        PlusBtn.setText("+");
        PlusBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        PlusBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        PlusBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        PlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusBtnActionPerformed(evt);
            }
        });

        Sevenbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Sevenbtn.setText("7");
        Sevenbtn.setMaximumSize(new java.awt.Dimension(33, 33));
        Sevenbtn.setMinimumSize(new java.awt.Dimension(33, 33));
        Sevenbtn.setPreferredSize(new java.awt.Dimension(24, 24));
        Sevenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenbtnActionPerformed(evt);
            }
        });

        Eightbtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Eightbtn.setText("8");
        Eightbtn.setMaximumSize(new java.awt.Dimension(33, 33));
        Eightbtn.setMinimumSize(new java.awt.Dimension(33, 33));
        Eightbtn.setPreferredSize(new java.awt.Dimension(24, 24));
        Eightbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightbtnActionPerformed(evt);
            }
        });

        Ninebtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Ninebtn.setText("9");
        Ninebtn.setMaximumSize(new java.awt.Dimension(33, 33));
        Ninebtn.setMinimumSize(new java.awt.Dimension(33, 33));
        Ninebtn.setPreferredSize(new java.awt.Dimension(24, 24));
        Ninebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NinebtnActionPerformed(evt);
            }
        });

        LessBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        LessBtn.setText("-");
        LessBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        LessBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        LessBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        LessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessBtnActionPerformed(evt);
            }
        });

        FourBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        FourBtn.setText("4");
        FourBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        FourBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        FourBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        FourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourBtnActionPerformed(evt);
            }
        });

        FiveBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        FiveBtn.setText("5");
        FiveBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        FiveBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        FiveBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        FiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveBtnActionPerformed(evt);
            }
        });

        SixBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        SixBtn.setText("6");
        SixBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        SixBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        SixBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        SixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixBtnActionPerformed(evt);
            }
        });

        Timebtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Timebtn.setText("*");
        Timebtn.setMaximumSize(new java.awt.Dimension(33, 33));
        Timebtn.setMinimumSize(new java.awt.Dimension(33, 33));
        Timebtn.setPreferredSize(new java.awt.Dimension(24, 24));
        Timebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimebtnActionPerformed(evt);
            }
        });

        OneBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        OneBtn.setText("1");
        OneBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        OneBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        OneBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        OneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneBtnActionPerformed(evt);
            }
        });

        TwoBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        TwoBtn.setText("2");
        TwoBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        TwoBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        TwoBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        TwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoBtnActionPerformed(evt);
            }
        });

        ThreeBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        ThreeBtn.setText("3");
        ThreeBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        ThreeBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        ThreeBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        ThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeBtnActionPerformed(evt);
            }
        });

        DivideBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        DivideBtn.setText("/");
        DivideBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        DivideBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        DivideBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        DivideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideBtnActionPerformed(evt);
            }
        });

        ZeroBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        ZeroBtn.setText("0");
        ZeroBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        ZeroBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        ZeroBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        ZeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroBtnActionPerformed(evt);
            }
        });

        DotBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        DotBtn.setText(".");
        DotBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        DotBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        DotBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        DotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotBtnActionPerformed(evt);
            }
        });

        EqualBtn.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        EqualBtn.setText("=");
        EqualBtn.setMaximumSize(new java.awt.Dimension(33, 33));
        EqualBtn.setMinimumSize(new java.awt.Dimension(33, 33));
        EqualBtn.setPreferredSize(new java.awt.Dimension(24, 24));
        EqualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqualBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DivideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CEbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sevenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eightbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ninebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Timebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sevenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eightbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ninebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Timebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers(String q){
        String Nums = Screen.getText() + q;
        Screen.setText(Nums);
    }
    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        String backSp = null;
        
        if(Screen.getText().length() > 0 ){
            StringBuilder sb = new StringBuilder(Screen.getText());
            sb.deleteCharAt(Screen.getText().length()-1);
            backSp = sb.toString();
            Screen.setText(backSp);
        }
    }//GEN-LAST:event_backspaceActionPerformed

    private void CbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbtnActionPerformed
        // TODO add your handling code here:
        Screen.setText("");
    }//GEN-LAST:event_CbtnActionPerformed

    private void CEbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEbtnActionPerformed
        // TODO add your handling code here:
        Screen.setText("");
        
        String Fn, Sn;
        Fn = String.valueOf(Number1);
        Sn = String.valueOf(Number2);
        
        Fn = ""; 
        Sn = "";
    }//GEN-LAST:event_CEbtnActionPerformed

    private void PlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusBtnActionPerformed
        // TODO add your handling code here:
        Number1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        Op = "+";
    }//GEN-LAST:event_PlusBtnActionPerformed

    private void SevenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenbtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("7");
    }//GEN-LAST:event_SevenbtnActionPerformed

    private void EightbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightbtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_EightbtnActionPerformed

    private void NinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NinebtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_NinebtnActionPerformed

    private void LessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessBtnActionPerformed
        // TODO add your handling code here:
        Number1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        Op = "-";
    }//GEN-LAST:event_LessBtnActionPerformed

    private void FourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_FourBtnActionPerformed

    private void FiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_FiveBtnActionPerformed

    private void SixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_SixBtnActionPerformed

    private void TimebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimebtnActionPerformed
        // TODO add your handling code here:
        Number1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        Op = "*";
    }//GEN-LAST:event_TimebtnActionPerformed

    private void OneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_OneBtnActionPerformed

    private void TwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_TwoBtnActionPerformed

    private void ThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_ThreeBtnActionPerformed

    private void DivideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideBtnActionPerformed
        // TODO add your handling code here:
        Number1 = Double.parseDouble(Screen.getText());
        Screen.setText("");
        Op = "/";
    }//GEN-LAST:event_DivideBtnActionPerformed

    private void ZeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroBtnActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_ZeroBtnActionPerformed

    private void DotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotBtnActionPerformed
        // TODO add your handling code here:
        if(! Screen.getText().contains(".")){
            Screen.setText(Screen.getText() + DotBtn.getText());
            
        }
    }//GEN-LAST:event_DotBtnActionPerformed

    private void EqualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualBtnActionPerformed
        // TODO add your handling code here:
        Number2 = Double.parseDouble(Screen.getText());
        switch(Op){
            case "+":
                Result = Number1 + Number2;
                Screen.setText(String.valueOf("= "+Result));
                break;
            case "-":
                Result = Number1 - Number2;
                Screen.setText(String.valueOf("= "+Result));
                break;
            case "/":
                Result = Number1 / Number2;
                Screen.setText(String.valueOf("= "+Result));
                break;
            case "*":
                Result = Number1 * Number2;
                Screen.setText(String.valueOf("= "+Result));
                break;
        }
                    
    }//GEN-LAST:event_EqualBtnActionPerformed

    private void ScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorDragDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorDragDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorDragDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorDragDrop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorDragDrop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CEbtn;
    private javax.swing.JButton Cbtn;
    private javax.swing.JButton DivideBtn;
    private javax.swing.JButton DotBtn;
    private javax.swing.JButton Eightbtn;
    private javax.swing.JButton EqualBtn;
    private javax.swing.JButton FiveBtn;
    private javax.swing.JButton FourBtn;
    private javax.swing.JButton LessBtn;
    private javax.swing.JButton Ninebtn;
    private javax.swing.JButton OneBtn;
    private javax.swing.JButton PlusBtn;
    private javax.swing.JTextField Screen;
    private javax.swing.JButton Sevenbtn;
    private javax.swing.JButton SixBtn;
    private javax.swing.JButton ThreeBtn;
    private javax.swing.JButton Timebtn;
    private javax.swing.JButton TwoBtn;
    private javax.swing.JButton ZeroBtn;
    private javax.swing.JButton backspace;
    // End of variables declaration//GEN-END:variables
}
